type Answers = Record<string, string>;

const safe = (v: string | undefined) => (v && v.trim() ? v.trim() : "[TBD]");

export function generateIdentityMarkdown(a: Answers): string {
  const today = new Date().toISOString().slice(0, 10);
  const name = safe(a.name);
  const titleCo = safe(a.title_company);

  return `# Identity — ${name}

> Generated by Voiceprint intake. Save this file as \`identity.md\` in your Voiceprint project folder. Update it as your voice sharpens.

---

## 1. Who you are

**Name / title / company:** ${titleCo}

**One-sentence positioning:**
${safe(a.positioning)}

---

## 2. Who you serve

**Ideal client:**
${safe(a.ideal_client)}

**What they came in saying:**
${safe(a.client_quotes)}

**What they say after working with you:**
${safe(a.after_quotes)}

---

## 3. What you actually do

**The hard problem you solve:**
${safe(a.hard_problem)}

**Your unfair advantage:**
${safe(a.unfair_advantage)}

**What you don't do:**
${safe(a.what_you_dont_do)}

---

## 4. Voice — in one sentence

${safe(a.voice_one_sentence)}

---

## 5. Voice pillars

${safe(a.voice_pillars)}

---

## 6. Vocabulary

### Phrases you actually say
${safe(a.phrases_you_say)}

### Phrases that sound like you, but aren't
${safe(a.phrases_close)}

### Banned words and phrases
${safe(a.banned_phrases)}

---

## 7. Content themes

${safe(a.themes)}

### Why you have a take on each
${safe(a.themes_why)}

---

## 8. Source artifacts

${safe(a.artifacts)}

---

## 9. Hashtag strategy

${safe(a.hashtags)}

---

## 10. Sign-off

${safe(a.signoff)}

---

## 11. Voice check — the three questions

Before any post ships, the model runs these:

1. **Would you actually say this out loud?** If it sounds like a press release, rewrite.
2. **Is there a specific moment, person, or number?** If everything is abstract, it won't land.
3. **Does it sound like ${a.gold_standard ? `"${a.gold_standard.split("\n")[0]}"` : "your gold-standard reference"}?**

---

*Generated ${today} by voiceprint-app.vercel.app intake. Source of truth for your voice. Update whenever you catch yourself thinking "the AI got that wrong."*
`;
}
